# Generated by Django 2.2.6 on 2021-01-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shelter', '0002_auto_20210111_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('Unknown', 'Unknown')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(blank=True, choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Rabbit', 'Rabbit')], max_length=100),
        ),
    ]
