# Generated by Django 2.2.6 on 2021-01-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shelter', '0005_auto_20210114_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='species2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pet_shelter.Species'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(blank=True, choices=[('Собаки', 'Собаки'), ('Коты и кошки', 'Коты и кошки'), ('Кролики', 'Кролики')], max_length=100, null=True),
        ),
    ]
