# Generated by Django 2.2.6 on 2021-01-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shelter', '0006_auto_20210114_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='species2',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
