# Generated by Django 2.2.6 on 2021-01-14 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shelter', '0009_remove_pet_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pet_shelter.Species'),
        ),
    ]
