# Generated by Django 2.2.6 on 2021-01-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shelter', '0010_pet_species'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Species',
            new_name='Specie',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='species',
            new_name='specie',
        ),
    ]
